<div class="row">
<a href="cars.php">
	<div class="col-md-12 col-sm-12 col-xs-12" style="height: auto; padding: 0;">
		<div class="col-md-4 hidden-xs hidden-sm" style="text-align: left;  padding: 0;">
			<img src="images/logo.gif" width="auto" height="100%">
		</div>
		
		<div class="col-md-4 col-sm-6 col-xs-12">
			<img src="images/link.png" width="auto" height="auto">
		</div>

		<div class="col-md-4 col-sm-6 hidden-xs" style="overflow: hidden;">
			<img src="images/logo.png" height="auto">
		</div>
	</div>
</a>
</div>	